version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build and push Docker image
          command: |
            docker build -t alexmarchant/oscars-2019-spa:latest .
            echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
            docker push alexmarchant/oscars-2019-spa:latest
      - run:
          name: Deploy app to Kubernetes
          command: |
            kubectl patch deployment oscars-2019-spa -p "{\"spec\":{\"template\":{\"metadata\":{\"labels\":{\"date\":\"`date +'%s'`\"}}}}}"
