export const constants = {
  AUTH_START: 'AUTH_START',
  AUTH_SUCCESS: 'AUTH_SUCCESS',
  AUTH_FAIL: 'AUTH_FAIL',
  AUTH_LOGOUT: 'AUTH_LOGOUT',
  HIGHLIGHT_SELECTION: 'HIGHLIGHT_SELECTION',
  UPDATE_SELECTION_STATE: 'UPDATE_SELECTION_STATE',
  LOAD_USER_PICKS: 'LOAD_USER_PICKS',
  IS_AUTHENTICATED: 'IS_AUTHENTICATED',
  LOAD_ALL_USERS: 'LOAD_ALL_USERS',
  GET_USERS_START: "GET_USERS_START",
  GET_USERS_SUCCESS: "GET_USERS_SUCCESS",
  GET_USERS_FAILURE: "GET_USERS_FAILURE"
}

export * from './alert.constants';
export * from './user.constants'
